# Generated by Django 4.0.5 on 2022-06-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_issue', models.CharField(max_length=128)),
                ('description_issue', models.CharField(max_length=128)),
                ('tag_issue', models.CharField(max_length=128)),
                ('priority_issue', models.CharField(max_length=128)),
                ('status_issue', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'issues',
            },
        ),
    ]
